color: null
description: null
fieldLayouts:
  b67bff09-269c-48ae-a788-b47d0a1f3768:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-15T15:55:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0b43d59e-9972-45ae-b1c8-a655f8d02e77
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-19T13:05:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1e549a1-8d29-46e7-8a2b-61c927402b01 # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0e509cb-7a77-4393-b6ec-735efb27bc72
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-18T18:41:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1ee0761f-66e1-4a6f-989c-9a99529fea4b # Hoofding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ffdf8ef-1503-4e78-8609-bdaca0c3d426
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T15:57:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bf5b3ff2-3bf8-469a-abc8-9ed41965380e # Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6026a1a-cb92-4946-928a-5015eb58c7bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-19T13:27:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bf5b3ff2-3bf8-469a-abc8-9ed41965380e # Tekst
            handle: formText
            includeInCards: false
            instructions: null
            label: 'Tekst boven het formulier'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfc06874-55c6-4cf5-803e-6ba10dad29cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-16T14:30:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a489d99e-553f-4af5-863d-0e65b8423a1a # Formulier
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ad6ce72-b1c2-4f51-a769-27702725b035
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: b3686f46-5b53-42e6-8d8c-34f8800f8e0d
        userCondition: null
handle: intro
hasTitleField: true
icon: null
name: Intro
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
