css: "text-primary\r\ntext-black"
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  heading:
    options:
      -
        class: ck-heading_paragraph
        model: paragraph
        title: Paragraph
      -
        class: text-black
        model: heading3
        title: 'Heading 3 (zwart)'
        view: h3
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
