altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ac74d4d7-b6f8-4520-a14a-461c04a5abde:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-19T13:03:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1af18ea1-40c7-4b7b-b213-3762767565f8
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 0f469136-6913-4ae9-b085-fb56720d4159
        userCondition: null
fs: images
handle: images
name: Afbeeldingen
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
