columnSuffix: null
handle: seoImage
instructions: null
name: 'SEO Afbeelding'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:45b6867a-8b2b-4aa8-9497-0718c5eb402f' # Afbeeldingen
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 0
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:45b6867a-8b2b-4aa8-9497-0718c5eb402f' # Afbeeldingen
  restrictedLocationSubpath: null
  selectionLabel: 'Voeg een afbeelding toe'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
