dateModified: 1768761672
email:
  fromEmail: info@tar-mac.be
  fromName: Tarmac
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1ee0761f-66e1-4a6f-989c-9a99529fea4b: Hoofding # Hoofding
    2a11be86-2613-4b12-9a8e-10dc9eca0936: Tickets # Tickets
    a3d62d30-84eb-428e-9608-f556fb668979: Tarmac # Tarmac
    a489d99e-553f-4af5-863d-0e65b8423a1a: Formulier # Formulier
    a7024844-b4d2-4359-b6c4-9e96d1410f28: Tarmac # Tarmac
    ae5775c3-6e0d-472d-89bf-78a0cb6e87d5: Simple # Simple
    bf5b3ff2-3bf8-469a-abc8-9ed41965380e: Tekst # Tekst
    d69e7ed5-a19d-4217-b60a-b4429c10f5ff: Intro # Intro
    dde55f52-a313-4f67-ac94-159629bcc3c1: Tickets # Tickets
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields: ''
      from_email: tickets@tar-mac.be
      from_name: Tarmac
      recaptcha_min_score: '0.5'
      recaptcha_public: 6LeybE4sAAAAADcKleKQ3ehjH2-LzBwzawfjBjYP
      recaptcha_secret: 6LeybE4sAAAAAGdafB6-e0j1NLnV8MuqWSIR0zcr
      recaptcha_version: '3'
      success_message: 'Bedankt voor je bestelling! In je mailbox vind je normaal alle verder info!'
      volume_id: ''
system:
  edition: solo
  live: true
  name: Tarmac
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
