dateModified: 1768224861
email:
  fromEmail: website@tar-mac.be
  fromName: Tarmac
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    a3d62d30-84eb-428e-9608-f556fb668979: Tarmac # Tarmac
    a7024844-b4d2-4359-b6c4-9e96d1410f28: Tarmac # Tarmac
system:
  edition: solo
  live: true
  name: Tarmac
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
