defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d69e7ed5-a19d-4217-b60a-b4429c10f5ff # Intro
  -
    uid: 3426a026-9598-4a86-97e4-117abdfb0cff
handle: tickets
maxAuthors: 1
name: Tickets
previewTargets:
  -
    label: 'Primaire invoer-pagina'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  2a11be86-2613-4b12-9a8e-10dc9eca0936: # Tickets
    enabledByDefault: true
    hasUrls: true
    template: tickets/index.twig
    uriFormat: __home__
  a3d62d30-84eb-428e-9608-f556fb668979: # Tarmac
    enabledByDefault: true
    hasUrls: true
    template: tickets/index.twig
    uriFormat: tickets
type: single
